-- Tabla de Tareas
CREATE TABLE tasks(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Productos
CREATE TABLE products(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    productName VARCHAR(200) NOT NULL,
    imgURL VARCHAR(1000),
    imgPublic_id VARCHAR(1000),
    description VARCHAR(700),
    price DOUBLE NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);